/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Thursday, September 20, 2018 at 2:31:03 PM
   By task:     Import Data Wizard
   
   Source file:
   E:\Geriatrics\ECHOChicagoGeriatricsSurvey_DataDictionary_2018-09-
   19tab.txt
   Server:      Local File System
   
   Output data: WORK.ECHOCHICAGOGERIATRICSSURVEY_0001
   Server:      Local

* Revision History  :
*
* Date        Author      Ref    Purpose
* 9/21/2018	Sandra Tilmon	 1	Generic import of data dictionary and 
								SAS data based on parameters in echo master
-------------------------------------------------------------------- */

/*  -------------------------------------------------------------------- *
	Run RedCap-generated SAS program to import SASa data. 
	Includery is "&Path.\&sasprog." from Master Control 
*  -------------------------------------------------------------------- */

*%put &RawData. ;

%include "&includery." ;

*%include "Z:\groups\ECHO-Chicago\Data\Raw\RedCap\Geri\GeriatricsPrimaryCar_SAS_2019-04-30_1559.sas" ;

DATA Redcap ; set redcap ; Project = "&Project." ; run ;
DATA &Project..Redcap ; set redcap ; Project = "&Project." ; run ;

/*  -------------------------------------------------------------------- *
	Import data dictionary. Filename is "&Path.\&dict." from Master Control 
*  -------------------------------------------------------------------- */

DATA WORK.Dict&Project. ;
    LENGTH
        Variable         $ 31
        PrePost          $ 6
        Domain           $ 18
		Detail			$ 20
		Theme			$ 32
        Form_Name        $ 28
        Section_Header   $ 366
        Field_Type       $ 11
        Field_Label      $ 1965
        Choices__Calculations__OR_Slider $ 413
        Field_Note       $ 1
        Text_Validation_Type_OR_Show_Sli $ 12
        Text_Validation_Min $ 1
        Text_Validation_Max $ 1
        Identifier_      $ 1
        Branching_Logic__Show_field_only $ 126
        Required_Field_  $ 1
        Custom_Alignment $ 1
        Question_Number__surveys_only_ $ 1
        Matrix_Group_Name $ 18
        Matrix_Ranking_  $ 1
        Field_Annotation $ 14 ;
    LABEL
        Form_Name        = "Form Name"
        Section_Header   = "Section Header"
        Field_Type       = "Field Type"
        Field_Label      = "Field Label"
        Choices__Calculations__OR_Slider = "Choices, Calculations, OR Slider Labels"
        Field_Note       = "Field Note"
        Text_Validation_Type_OR_Show_Sli = "Text Validation Type OR Show Slider Number"
        Text_Validation_Min = "Text Validation Min"
        Text_Validation_Max = "Text Validation Max"
        Identifier_      = "Identifier?"
        Branching_Logic__Show_field_only = "Branching Logic (Show field only if...)"
        Required_Field_  = "Required Field?"
        Custom_Alignment = "Custom Alignment"
        Question_Number__surveys_only_ = "Question Number (surveys only)"
        Matrix_Group_Name = "Matrix Group Name"
        Matrix_Ranking_  = "Matrix Ranking?"
        Field_Annotation = "Field Annotation" ;
    FORMAT
        Variable         $CHAR31.
        PrePost          $CHAR6.
        Domain           $CHAR18.
		Detail			$CHAR20. 
		Theme			$CHAR31.
        Form_Name        $CHAR28.
        Section_Header   $CHAR366.
        Field_Type       $CHAR11.
        Field_Label      $CHAR1965.
        Choices__Calculations__OR_Slider $CHAR413.
        Field_Note       $CHAR1.
        Text_Validation_Type_OR_Show_Sli $CHAR12.
        Text_Validation_Min $CHAR1.
        Text_Validation_Max $CHAR1.
        Identifier_      $CHAR1.
        Branching_Logic__Show_field_only $CHAR126.
        Required_Field_  $CHAR1.
        Custom_Alignment $CHAR1.
        Question_Number__surveys_only_ $CHAR1.
        Matrix_Group_Name $CHAR18.
        Matrix_Ranking_  $CHAR1.
        Field_Annotation $CHAR14. ;
    INFORMAT
        Variable         $CHAR31.
        PrePost          $CHAR6.
        Domain           $CHAR18.
		Detail			$CHAR20. 
		Theme			$CHAR31.
        Form_Name        $CHAR28.
        Section_Header   $CHAR366.
        Field_Type       $CHAR11.
        Field_Label      $CHAR1965.
        Choices__Calculations__OR_Slider $CHAR413.
        Field_Note       $CHAR1.
        Text_Validation_Type_OR_Show_Sli $CHAR12.
        Text_Validation_Min $CHAR1.
        Text_Validation_Max $CHAR1.
        Identifier_      $CHAR1.
        Branching_Logic__Show_field_only $CHAR126.
        Required_Field_  $CHAR1.
        Custom_Alignment $CHAR1.
        Question_Number__surveys_only_ $CHAR1.
        Matrix_Group_Name $CHAR18.
        Matrix_Ranking_  $CHAR1.
        Field_Annotation $CHAR14. ;
    INFILE "Z:\groups\ECHO-Chicago\Data\Raw\RedCap\&Project.\&dict."
        LRECL=2059
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='09'x
        MISSOVER
        DSD FIRSTOBS=2 ;
    INPUT
        Variable         : $CHAR31.
        PrePost          : $CHAR6.
        Domain           : $CHAR18.
		Detail			: $CHAR20.
		Theme			: $CHAR31.
        Form_Name        : $CHAR28.
        Section_Header   : $CHAR366.
        Field_Type       : $CHAR11.
        Field_Label      : $CHAR1965.
        Choices__Calculations__OR_Slider : $CHAR413.
        Field_Note       : $CHAR1.
        Text_Validation_Type_OR_Show_Sli : $CHAR12.
        Text_Validation_Min : $CHAR1.
        Text_Validation_Max : $CHAR1.
        Identifier_      : $CHAR1.
        Branching_Logic__Show_field_only : $CHAR126.
        Required_Field_  : $CHAR1.
        Custom_Alignment : $CHAR1.
        Question_Number__surveys_only_ : $CHAR1.
        Matrix_Group_Name : $CHAR18.
        Matrix_Ranking_  : $CHAR1.
        Field_Annotation : $CHAR14. ;
RUN;

* Also save a permanent copy -- but leave the "work" copy. ;

DATA &Project..Dict&Project.;
 set WORK.Dict&Project. ;
 run ;
